name: flutter_chatsen_irc
description: IRC Client for Chatsen

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^0.13.3
  web_socket_channel: ^2.1.0
  collection: ^1.15.0

dev_dependencies:
  pedantic: ^1.11.0
